---
deployment:
  tasks:
    - cd /home/pigworldsmart/api.pigworldsmart.com
    - BACKEND_DIR=/home/pigworldsmart/api.pigworldsmart.com/app API_DOMAIN=api.pigworldsmart.com /bin/bash deploy-backend.sh