---
deployment:
  tasks:
    - BACKEND_DIR=/home/pigworldsmart/api.pigworldsmart.com/app API_DOMAIN=api.pigworldsmart.com CRM_DOMAIN=crm.pigworldsmart.com /bin/bash /home/pigworldsmart/api.pigworldsmart.com/deploy-backend.sh
