<?php

use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\CrmAdminController;
use App\Http\Controllers\Api\V1\CrmAuditLogController;
use App\Http\Controllers\Api\V1\CrmCustomerEventController;
use App\Http\Controllers\Api\V1\CrmDashboardController;
use App\Http\Controllers\Api\V1\CrmDirectoryController;
use App\Http\Controllers\Api\V1\CrmMemberController;
use App\Http\Controllers\Api\V1\CrmNotificationController;
use App\Http\Controllers\Api\V1\CrmPolicyController;
use App\Http\Controllers\Api\V1\CrmReportController;
use App\Http\Controllers\Api\V1\CrmStaffCategoryController;
use App\Http\Controllers\Api\V1\CrmSupportConversationController;
use App\Http\Controllers\Api\V1\CrmTaskController;
use App\Http\Controllers\Api\V1\CustomerController;
use App\Http\Controllers\Api\V1\CustomerInteractionController;
use App\Http\Controllers\Api\V1\CustomerOrderController;
use App\Http\Controllers\Api\V1\FarmController;
use App\Http\Controllers\Api\V1\FarmFinanceController;
use App\Http\Controllers\Api\V1\FarmJoinRequestController;
use App\Http\Controllers\Api\V1\FarmMemberController;
use App\Http\Controllers\Api\V1\FarmNameChangeRequestController;
use App\Http\Controllers\Api\V1\FarmNotificationController;
use App\Http\Controllers\Api\V1\FarmOverviewController;
use App\Http\Controllers\Api\V1\FarmSalesController;
use App\Http\Controllers\Api\V1\FarmSubscriptionController;
use App\Http\Controllers\Api\V1\FarmSupportConversationController;
use App\Http\Controllers\Api\V1\FarmTaskController;
use App\Http\Controllers\Api\V1\FeedController;
use App\Http\Controllers\Api\V1\GrowthController;
use App\Http\Controllers\Api\V1\HealthController;
use App\Http\Controllers\Api\V1\HerdController;
use App\Http\Controllers\Api\V1\InventoryController;
use App\Http\Controllers\Api\V1\MpesaPaymentController;
use App\Http\Controllers\Api\V1\PregnancyController;
use App\Http\Controllers\Api\V1\PigMarketplaceController;
use App\Http\Controllers\Api\V1\PushDeviceController;
use App\Http\Controllers\Api\V1\ReportsController;
use App\Http\Controllers\Api\V1\SubscriptionPlanController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::get('marketplace/pigs', [PigMarketplaceController::class, 'browse'])->middleware('throttle:60,1');
    Route::post('marketplace/pigs/{listing}/inquiries', [PigMarketplaceController::class, 'inquire'])->middleware('throttle:10,1');
    Route::post('marketplace/pigs/{listing}/buyer-inquiries', [PigMarketplaceController::class, 'buyerInquire'])->middleware(['auth:sanctum', 'throttle:10,1']);

    Route::middleware('throttle:auth')->group(function () {
        Route::post('/auth/register', [AuthController::class, 'register']);
        Route::post('/auth/login', [AuthController::class, 'login']);
        Route::post('/auth/verify-otp', [AuthController::class, 'verifyLoginOtp']);
        Route::post('/auth/resend-otp', [AuthController::class, 'resendLoginOtp']);
        Route::post('/auth/google', [AuthController::class, 'loginWithGoogle']);
        Route::post('/auth/firebase', [AuthController::class, 'loginWithFirebase']);
        Route::post('/auth/refresh', [AuthController::class, 'refresh']);
        Route::post('/auth/forgot-password', [AuthController::class, 'forgotPassword']);
        Route::post('/auth/reset-password', [AuthController::class, 'resetPassword']);
    });

    Route::middleware('auth:sanctum')->group(function () {
        Route::get('marketplace/buyer/deliveries', [PigMarketplaceController::class, 'buyerDeliveries']);
        Route::post('/auth/push-token', [PushDeviceController::class, 'store']);
        Route::delete('/auth/push-token', [PushDeviceController::class, 'destroy']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::patch('/auth/profile', [AuthController::class, 'updateProfile']);
        Route::post('/auth/profile/avatar', [AuthController::class, 'updateProfileAvatar']);
        Route::post('/auth/change-password', [AuthController::class, 'changePassword']);
        Route::get('/auth/join-requests', [FarmJoinRequestController::class, 'mine']);
        Route::post('farms', [FarmController::class, 'store']);
        Route::patch('farms/{farm}', [FarmController::class, 'update']);
        Route::get('farms/{farm}/name-change-requests', [FarmNameChangeRequestController::class, 'mine']);
        Route::post('farms/{farm}/name-change-requests', [FarmNameChangeRequestController::class, 'store']);
        Route::post('farm-join-requests', [FarmJoinRequestController::class, 'store']);
        Route::get('farms/{farm}/overview', [FarmOverviewController::class, 'show']);
        Route::get('farms/{farm}/feed', [FeedController::class, 'index']);
        Route::post('farms/{farm}/feed/stock', [FeedController::class, 'storeStock']);
        Route::post('farms/{farm}/feed/usage', [FeedController::class, 'storeUsage']);
        Route::get('farms/{farm}/notifications', [FarmNotificationController::class, 'index']);
        Route::post('farms/{farm}/notifications/messages', [FarmNotificationController::class, 'sendMessage']);
        Route::patch('farms/{farm}/notifications/{notification}/read', [FarmNotificationController::class, 'markAsRead']);
        Route::get('farms/{farm}/support-conversation', [FarmSupportConversationController::class, 'show']);
        Route::post('farms/{farm}/support-conversation/messages', [FarmSupportConversationController::class, 'storeMessage']);
        Route::patch('farms/{farm}/support-conversation/read', [FarmSupportConversationController::class, 'markAsRead']);
        Route::get('farms/{farm}/tasks', [FarmTaskController::class, 'index']);
        Route::post('farms/{farm}/tasks', [FarmTaskController::class, 'store']);
        Route::patch('farms/{farm}/tasks/{task}', [FarmTaskController::class, 'update']);
        Route::delete('farms/{farm}/tasks/{task}', [FarmTaskController::class, 'destroy']);
        Route::get('farms/{farm}/finance', [FarmFinanceController::class, 'index']);
        Route::post('farms/{farm}/finance', [FarmFinanceController::class, 'store']);
        Route::get('farms/{farm}/buyers', [FarmSalesController::class, 'buyers']);
        Route::post('farms/{farm}/buyers', [FarmSalesController::class, 'storeBuyer']);
        Route::patch('farms/{farm}/buyers/{buyer}', [FarmSalesController::class, 'updateBuyer']);
        Route::get('farms/{farm}/sales', [FarmSalesController::class, 'sales']);
        Route::post('farms/{farm}/sales', [FarmSalesController::class, 'storeSale']);
        Route::patch('farms/{farm}/sales/{sale}', [FarmSalesController::class, 'updateSale']);
        Route::get('farms/{farm}/pig-listings', [PigMarketplaceController::class, 'farmListings']);
        Route::post('farms/{farm}/pig-listings', [PigMarketplaceController::class, 'store']);
        Route::patch('farms/{farm}/pig-listings/{listing}', [PigMarketplaceController::class, 'updateStatus']);
        Route::patch('farms/{farm}/pig-listings/{listing}/inquiries/{inquiry}', [PigMarketplaceController::class, 'updateInquiryStatus']);

        Route::apiResource('crm/customers', CustomerController::class);
        Route::get('crm/tasks', [CrmTaskController::class, 'farmIndex']);
        Route::get('crm/customers/{customer}/interactions', [CustomerInteractionController::class, 'index']);
        Route::post('crm/customers/{customer}/interactions', [CustomerInteractionController::class, 'store']);
        Route::get('crm/customers/{customer}/tasks', [CrmTaskController::class, 'index']);
        Route::post('crm/customers/{customer}/tasks', [CrmTaskController::class, 'store']);
        Route::patch('crm/customers/{customer}/tasks/{task}', [CrmTaskController::class, 'update']);
        Route::delete('crm/customers/{customer}/tasks/{task}', [CrmTaskController::class, 'destroy']);
        Route::get('crm/customers/{customer}/timeline', [CrmCustomerEventController::class, 'timeline']);
        Route::get('crm/members', [CrmMemberController::class, 'index']);
        Route::get('crm/staff-categories', [CrmStaffCategoryController::class, 'index']);
        Route::post('crm/staff-categories', [CrmStaffCategoryController::class, 'store']);
        Route::delete('crm/staff-categories/{staffCategory}', [CrmStaffCategoryController::class, 'destroy']);
        Route::get('crm/policies', [CrmPolicyController::class, 'index']);
        Route::post('crm/policies', [CrmPolicyController::class, 'store']);
        Route::put('crm/policies/{policy}', [CrmPolicyController::class, 'update']);
        Route::get('crm/audit-logs', [CrmAuditLogController::class, 'index']);
        Route::get('crm/farm-name-change-requests', [FarmNameChangeRequestController::class, 'index']);
        Route::patch('crm/farm-name-change-requests/{farmNameChangeRequest}', [FarmNameChangeRequestController::class, 'review']);
        Route::post('crm/members', [CrmMemberController::class, 'store']);
        Route::patch('crm/members/{user}', [CrmMemberController::class, 'update']);
        Route::delete('crm/members/{user}', [CrmMemberController::class, 'destroy']);
        Route::get('crm/notifications', [CrmNotificationController::class, 'index']);
        Route::post('crm/notifications', [CrmNotificationController::class, 'store']);
        Route::get('crm/broadcasts', [CrmNotificationController::class, 'broadcasts']);
        Route::get('crm/admin/farms', [CrmAdminController::class, 'farms']);
        Route::get('crm/admin/prospects', [CrmAdminController::class, 'prospects']);
        Route::post('crm/admin/prospects', [CrmAdminController::class, 'storeProspect']);
        Route::patch('crm/admin/prospects/{prospect}', [CrmAdminController::class, 'updateProspect']);
        Route::delete('crm/admin/prospects/{prospect}', [CrmAdminController::class, 'deleteProspect']);
        Route::get('crm/admin/notification-templates', [CrmAdminController::class, 'templates']);
        Route::post('crm/admin/notification-templates', [CrmAdminController::class, 'storeTemplate']);
        Route::patch('crm/admin/notification-templates/{template}', [CrmAdminController::class, 'updateTemplate']);
        Route::delete('crm/admin/notification-templates/{template}', [CrmAdminController::class, 'deleteTemplate']);
        Route::get('crm/support-conversations', [CrmSupportConversationController::class, 'index']);
        Route::get('crm/support-conversations/{conversation}', [CrmSupportConversationController::class, 'show']);
        Route::post('crm/support-conversations/{conversation}/messages', [CrmSupportConversationController::class, 'storeMessage']);
        Route::patch('crm/support-conversations/{conversation}', [CrmSupportConversationController::class, 'update']);
        Route::patch('crm/support-conversations/{conversation}/read', [CrmSupportConversationController::class, 'markAsRead']);
        Route::get('crm/dashboard/overview', [CrmDashboardController::class, 'overview']);
        Route::get('crm/directories/overview', [CrmDirectoryController::class, 'overview']);
        Route::get('crm/orders', [CustomerOrderController::class, 'index']);
        Route::post('crm/orders', [CustomerOrderController::class, 'store']);
        Route::get('crm/orders/{order}', [CustomerOrderController::class, 'show']);
        Route::patch('crm/orders/{order}', [CustomerOrderController::class, 'update']);
        Route::get('crm/reports/overview', [CrmReportController::class, 'overview']);
        Route::get('subscription-plans', [SubscriptionPlanController::class, 'index']);
        Route::post('subscription-plans', [SubscriptionPlanController::class, 'store']);
        Route::patch('subscription-plans/{subscription_plan}', [SubscriptionPlanController::class, 'update']);
        Route::delete('subscription-plans/{subscription_plan}', [SubscriptionPlanController::class, 'destroy']);

        Route::get('farms/{farm}/members', [FarmMemberController::class, 'index']);
        Route::patch('farms/{farm}/members/{user}', [FarmMemberController::class, 'update']);
        Route::get('farms/{farm}/join-requests', [FarmJoinRequestController::class, 'index']);
        Route::patch('farms/{farm}/join-requests/{farmJoinRequest}', [FarmJoinRequestController::class, 'review']);
        Route::patch('farms/{farm}/subscription', [FarmSubscriptionController::class, 'update']);
        Route::get('farms/{farm}/payments', [FarmSubscriptionController::class, 'payments']);
        Route::post('farms/{farm}/subscription/payment', [MpesaPaymentController::class, 'store']);
        Route::get('farms/{farm}/animals', [HerdController::class, 'index']);
        Route::post('farms/{farm}/animals', [HerdController::class, 'store']);
        Route::get('farms/{farm}/animals/{animal}', [HerdController::class, 'show']);
        Route::get('farms/{farm}/animals/{animal}/report', [ReportsController::class, 'animalReport']);
        Route::patch('farms/{farm}/animals/{animal}', [HerdController::class, 'update']);
        Route::delete('farms/{farm}/animals/{animal}', [HerdController::class, 'destroy']);

        Route::apiResource('farms/{farm}/pregnancies', PregnancyController::class)
            ->except(['create', 'edit']);

        Route::get('farms/{farm}/health-records', [HealthController::class, 'index']);
        Route::post('farms/{farm}/health-records', [HealthController::class, 'store']);
        Route::get('farms/{farm}/health-records/{healthRecord}', [HealthController::class, 'show']);
        Route::patch('farms/{farm}/health-records/{healthRecord}', [HealthController::class, 'update']);
        Route::delete('farms/{farm}/health-records/{healthRecord}', [HealthController::class, 'destroy']);
        Route::get('farms/{farm}/health-alerts', [HealthController::class, 'getAlerts']);
        Route::get('farms/{farm}/health-analytics', [HealthController::class, 'getAnalytics']);

        Route::get('farms/{farm}/growth-records', [GrowthController::class, 'index']);
        Route::post('farms/{farm}/growth-records', [GrowthController::class, 'store']);
        Route::get('farms/{farm}/growth-records/{growthRecord}', [GrowthController::class, 'show']);
        Route::patch('farms/{farm}/growth-records/{growthRecord}', [GrowthController::class, 'update']);
        Route::delete('farms/{farm}/growth-records/{growthRecord}', [GrowthController::class, 'destroy']);
        Route::get('farms/{farm}/growth-overview', [GrowthController::class, 'getOverview']);
        Route::get('farms/{farm}/growth-analytics', [GrowthController::class, 'getAnalytics']);
        Route::get('farms/{farm}/reports/metrics', [ReportsController::class, 'metrics']);

        // Inventory Routes
        Route::get('farms/{farm}/inventory/items', [InventoryController::class, 'index']);
        Route::post('farms/{farm}/inventory/items', [InventoryController::class, 'store']);
        Route::get('farms/{farm}/inventory/items/{item}', [InventoryController::class, 'show']);
        Route::patch('farms/{farm}/inventory/items/{item}', [InventoryController::class, 'update']);
        Route::delete('farms/{farm}/inventory/items/{item}', [InventoryController::class, 'destroy']);
        Route::post('farms/{farm}/inventory/items/{item}/movements', [InventoryController::class, 'recordMovement']);
        Route::get('farms/{farm}/inventory/items/{item}/movements', [InventoryController::class, 'getMovements']);
        Route::get('farms/{farm}/inventory/alerts', [InventoryController::class, 'getAlerts']);
        Route::get('farms/{farm}/inventory/by-category', [InventoryController::class, 'getByCategory']);
    });

    Route::post('payments/mpesa/callback', [MpesaPaymentController::class, 'callback']);
});
